kubernetes-sigs/ip-masq-agent

- cmd/ip-masq-agent/ip-masq-agent.go
It was tested before jumping to this chain.
Minor, but will need a rebuild, push, and update main kube repo for version.
> Don't re-test addrtype on every rule

- OWNERS
> Add myself as a reviewer and approver so I can help with PRs and issues

- cmd/ip-masq-agent/ip-masq-agent.go
Ref https://github.com/kubernetes-incubator/ip-masq-agent/pull/22#issuecomment-427141115. It makes more sense to log the error and retry, instead of crashing the container and let kubelet handle the restart:
- Restart doesn't help resolving most of the situations (e.g. iptables lock is hold).
- Unnecessary crashlooping generates false alerts given this is likely a kube-system pod.
Fixes https://github.com/kubernetes-incubator/ip-masq-agent/issues/23.
/assign @jingax10
cc @negz
> Only log but don't exit on error

- Makefile
This will allow the ip-masq-agent DaemonSet to work on any arch out of the box (in a follow-up PR) by using a multi-arch image (manifest list).
We're planning to use the agent for http://github.com/kubernetes-sigs/kind and nominally support ADM64, ARM64 and PPCLE64 for testing, this change will make using the agent simpler.
An example is at: `gcr.io/bentheelder-kind-dev/ip-masq-agent:v2.3.0-1-g51408b3`, produced with `make all-push REGISTRY=gcr.io/bentheelder-kind-dev`.
/cc @MrHohn
> push a multi-arch image

- README.md
- agent-config/config
- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
Add support for ipv6.
This is to add support for the dual stack feature - 
https://github.com/kubernetes/kubernetes/pull/78801
https://github.com/kubernetes/kubernetes/pull/79386
cc @khenidak
> Support for IPv6

- cmd/ip-masq-agent/ip-masq-agent.go
Comment change. No code change included.
> Update RFC references for reserved IP ranges.

- Makefile
> bump debian-iptables versions to v12.0.1

- Makefile
> Bump iptables-distroless to v0.2.1

- .gitignore
- Dockerfile.in
> Fix go-build-template update: iptables can't run as nobody

- cmd/ip-masq-agent/ip-masq-agent.go
> Output version and flags received at startup

- Makefile
> Bump base image to distroless-iptables v0.2.5

- Makefile
> Bump distroless-iptables to v0.3.1 and Go to 1.21

- .github/workflows/crossbuild.yaml
- .github/workflows/tests.yaml
> Add Go 1.21 to test matrix

- .github/workflows/crossbuild.yaml
- .github/workflows/tests.yaml
- Makefile
- go.mod
> Bump to Go 1.22 and distroless-iptables:v0.4.4

- go.mod
- pkg/interval/interval.go
- pkg/interval/interval_test.go
> Implement pkg/interval in preparation for --to-ports

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
> Implement --to-ports flag to specify explicit masquerading to-ports

- README.md
> Update README.md for --random-fully and --to-ports flags

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
> Don't set --random-fully if it's not supported even if the flag is true

- Makefile
> Bump base image to distroless-iptables:v0.6.4

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
> Switch away from home-made Duration type

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
> Fix lint failures introduced by #181

- cmd/ip-masq-agent/ip-masq-agent.go
> Log the exact error message in case of config file "not found"

- Makefile
> Bump base image to distroless-iptables:v0.6.9

- go.mod
> go mod tidy && go mod vendor

- Makefile
> Bump base image to distroless-iptables:v0.7.7
