- cmd/ip-masq-agent/ip-masq-agent.go
Since the config file is optional logging may be superfluous
in most siutations, especially considering this runs frequently.
Fixes https://github.com/mtaufen/ip-masq-agent/issues/2
Wondering also if we should remove that repo since it may be confusing since folks are filing issues there?
> Update logging to be debug only.

- Makefile
Without --pull, it's possible to use old base images which may have fixed vulnerabilities upstream.
x-ref kubernetes/kubernetes#47386
After merging this, we should probably create a new tag and then rebuild the image.
> Always --pull during docker build

- README.md
This updates the readme to reflect the current ownership of ip-masq-agent.
> update readme with current owners

- Makefile
Avoid using docker run -t in docker-in-docker builds
> make: add condition to use docker run -t flag

- Makefile
Match the version used by kube-proxy from PR k/k #75845
https://github.com/kubernetes/kubernetes/pull/75845
> Bump the version of debian-iptables-amd64 to pick up some CVE fixes

- README.md
- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
Adds a startup flag to change the default nonMasqueradeCidrs from the
RFC1918 ranges to all reserved ranges when the configMap has no
nonMasqueradeCidrs key.
The flag is defaulted to `false`, which maintains the current behavior.
The full list of reserved ranges are
10.0.0.0/8: RFC 1918
172.16.0.0/12: RFC 1918
192.168.0.0/16: RFC 1918
100.64.0.0/10: RFC 6598
192.0.0.0/24: RFC 6890
192.0.2.0/24: RFC 5737
192.88.99.0/24: RFC 7526
198.18.0.0/15: RFC 2544
203.0.113.0/24: RFC 5737
240.0.0.0/4: Former Class E range obsoleted by RFC 3232
> Add support to ip-masq-agent to avoid masquerading any RFC reserved range by default

- ip-masq-agent.yaml
fixes #28 
I looked around and as far as i can tell you need `CAP_NET_ADMIN` and `CAP_NET_RAW` to manage iptables. This works in https://github.com/kubernetes-sigs/kind/pull/500
> use capabilities instead of privileged

- Makefile
- use k8s.gcr.io for all images (Eventually this may not point to `gcr.io/google-containers`)
- use the debian-iptables image on all architectures instead of debian-base on not-amd64, I suspect the images for other architectures don't work currently
> correct base-images

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
`net.ParseCIDR` already validates correctly and handles IPv6
/cc @MrHohn
> just use ParseCIDR to validate CIDRs instead of regex

- README.md
- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
This adds the missing 198.51.100.0/24 as a complement of https://github.com/kubernetes-incubator/ip-masq-agent/pull/33.
> Add 198.51.100.0/24 to default non-masq IP ranges.

- Makefile
The makefile currently points to `gcr.io/google-container`, which is incorrect as we need to push to staging registry first.
> Push to k8s staging registry

- ip-masq-agent.yaml
Kubernetes 1.16 dropped support for DaemonSets in extensions/v1beta1, and apps/v1 now expects a non-empty selector.
> Update manifest to work with k8s 1.16

- OWNERS
- SECURITY_CONTACTS
For kubernetes/org#2013
As a part of cleaning up inactive members (who haven't been active since
the release of v1.11) from OWNERS, this commit removes dnardo from
the OWNERS and SECURITY_CONTACTS files.
/assign @MrHohn 
cc @mrbobbytables @dnardo
> Remove inactive members from OWNERS and SECURITY_CONTACTS

- Makefile
- RELEASE.md
Use the new gcr.io/k8s-staging-networking registry to push staging images.
Update instructions to add a line to kubernetes/k8s.io/k8s.gcr.io/images/k8s-staging-networking/images.yaml to push to the final location
Update the final location to be k8s.gcr.io/networking/ip-masq-agent-*
> Update release instructions to follow the new k8s.io staging repo model

- Makefile
Updating to use the latest base image available from https://github.com/kubernetes/release/blob/master/images/build/debian-iptables/Makefile.
/assign @varunmar
> Bump up the iptables base image to pick up CVE fixes.

- CONTRIBUTING.md
Link for " instructions to add a dependency" was outdated and broken in https://github.com/kundan2707/ip-masq-agent/blob/master/CONTRIBUTING.md
> updated link for instructions to add a dependency

- ip-masq-agent.yaml
This fixes https://github.com/kubernetes-sigs/ip-masq-agent/issues/76.
/cc @jingyuanliang
> Update manifest to point to the prod 2.7.0 image.

- Makefile
k8s.gcr.io/build-image/debian-iptables:bullseye-v1.5.0 is an multiarch
manifest so we no longer use the -$(ARCH) version.
> Bump base image to bullseye-v1.5.0 to pick up CVE fixes

- Makefile
- ip-masq-agent.yaml
Also incorporated buildx from GoogleCloudPlatform/netd@cf82473 which should fix the `exec format error` for non-AMD64 images.
/assign @MrHohn 
/hold
> Switch base image to k8s.gcr.io/build-image/distroless-iptables:v0.1.1

- cmd/ip-masq-agent/ip-masq-agent.go
Use base 10 integer variable interpolation instead of base 2.
> fix cidrlimit error log output

- Makefile
- go.mod
/assign @jingyuanliang 
Ref https://github.com/kubernetes-sigs/ip-masq-agent/issues/94 - we will likely abadon v2.9.0 and make a v2.9.1 after this.
Fixes https://github.com/kubernetes-sigs/ip-masq-agent/issues/96.
> Bump go version to 1.19 to pick up a few CVE fixes.

- .gitignore
`make container` generates `.buildx-initalized` file. adding to gitignore to avoid non-clean git state
> add .buildx-initalized to .gitignore

- RELEASE.md
- ip-masq-agent.yaml
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
This PR replaces all `k8s.gcr.io` references with `registry.k8s.io`. See the linked issue for more details.
**Which issue(s) this PR fixes**:
xref https://github.com/kubernetes/k8s.io/issues/4738
**Release note**:
```
Replace all `k8s.gcr.io` references with `registry.k8s.io`
```
> Replace k8s.gcr.io with registry.k8s.io

- RELEASE.md
> Update RELEASE.md to match the current Makefile

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
- cmd/ip-masq-agent/testing/fakefs/fakefs.go
> Fix lint failures, including setting nolint:errcheck on test

- .github/workflows/crossbuild.yaml
- .github/workflows/tests.yaml
We'll have to keep go version in go.mod at the latest, to ensure golang compatibility support throughout the release lifetime. However this breaks buildability with older golang images, since Go 1.21.
> Remove GO_VERSION test matrix

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
Defaults to true to keep the behavior added in 2.10.0 unchanged.
> Add --random-fully=true|false flag to ip-masq-agent

- cmd/ip-masq-agent/ip-masq-agent.go
- cmd/ip-masq-agent/ip-masq-agent_test.go
- vendor/k8s.io/component-base/logs/logreduction/logreduction.go
- vendor/modules.txt
We now have many toggles to adjust the rules. Having them dumped in logs helps debugging and eliminates the need to inspect nodes in many cases.
> Log generated iptables rules too in addition to the original config file

- cmd/ip-masq-agent/ip-masq-agent.go
I believe the original issue occurred because the whole (after "-m")
" comment --comment ..." string was parsed as the module name (in place
of "comment"). It's not possible to put unparsed string in the args,
because it doesn't go through a shell.
Also removed the unnecessary quote; I think it was there because we
assumed it's passing through the shell (so that words get split).
/assign @MrHohn @mtaufen
> Replace comment that's no longer relevant
